# Generated by Django 4.0.3 on 2022-03-31 15:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservations', '0003_reservation_adults_reservation_kids'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservation',
            name='departure_date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='entrance_date',
            field=models.DateField(),
        ),
    ]
