# Generated by Django 4.0.3 on 2022-03-17 15:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accommodations', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accommodation',
            name='name',
            field=models.CharField(max_length=140, verbose_name='Accommodation name'),
        ),
        migrations.AlterField(
            model_name='image',
            name='accommodations',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='accommodations.accommodation'),
        ),
    ]
